version: '3'

services:
  dockerauth:
    image: cesanta/docker_auth
    ports:
      - "5001:5001"
    environment:
      BULLSEYE_WEB_URL: $BULLSEYE_WEB_URL
      BULLSEYE_API_AUTH_TOKEN: $BULLSEYE_API_AUTH_TOKEN
    volumes:
      - ./config:/config:ro
      - ./log:/logs
    command: /config/registry_auth_config.yml
    restart: always
    depends_on:
      - registry

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH_TOKEN_REALM: https://$DOCKER_REGISTRY_AUTH_HOST/auth
      REGISTRY_NOTIFICATION_ENDPOINT: $BULLSEYE_WEB_URL/internal_api/v1/registry_event
      REGISTRY_NOTIFICATION_TOKEN: "Bearer $BULLSEYE_API_AUTH_TOKEN"
    volumes:
      - ./data:/var/lib/registry
      - ./config/certs:/certs:ro
      - ./config/registry_config.yml:/etc/docker/registry/config.yml:ro
