version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/server.crt
    key: /certs/server.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  token:
    realm: _env:REGISTRY_AUTH_TOKEN_REALM
    service: "Docker registry"
    issuer: "Auth Service"
    rootcertbundle: /certs/server.crt
notifications:
  endpoints:
    - name: bullseye-web
      url: _env:REGISTRY_NOTIFICATION_ENDPOINT
      headers:
        Authorization: [_env:REGISTRY_NOTIFICATION_TOKEN]