server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/config/certs/server.crt"
  key: "/config/certs/server.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900

ext_auth:
  command: "/config/ext_auth.sh"

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["pull", "push"]
